#include "engine.hpp"
#include "resource.h"
#include "settings.hpp"
#include "keymap.hpp"
#include "layout_mgr.hpp"
#include "replacer.hpp"
#include "secure_input.hpp"
#include "selection.hpp"
#include "snippets.hpp"
#include "double_space.hpp"
#include "caps_remap.hpp"
#include "sound.hpp"
#include "logger.hpp"
#include <psapi.h>

namespace Ultimakey {

Engine& Engine::Instance() {
    static Engine instance;
    return instance;
}

Engine::Engine() = default;
Engine::~Engine() = default;

static bool LoadResourceBlob(HINSTANCE hinstance, int res_id, const void*& out_ptr, size_t& out_size) {
    HRSRC hres = FindResourceW(hinstance, MAKEINTRESOURCEW(res_id), MAKEINTRESOURCEW(10));
    if (!hres) return false;
    out_size = SizeofResource(hinstance, hres);
    HGLOBAL hdata = LoadResource(hinstance, hres);
    if (!hdata) return false;
    out_ptr = LockResource(hdata);
    return (out_ptr != nullptr && out_size > 0);
}

static void CALLBACK WinEventProc(HWINEVENTHOOK /*hWinEventHook*/, DWORD event, HWND hwnd,
                                  LONG /*idObject*/, LONG /*idChild*/, DWORD /*idEventThread*/, DWORD /*dwmsEventTime*/) {
    if (event == EVENT_SYSTEM_FOREGROUND && hwnd) {
        Engine::Instance().OnForegroundChanged(hwnd);
    }
}

bool Engine::Initialize(HINSTANCE hinstance) {
    Logger::Instance().Write("Engine: Инициализация...");

    const void* ptr = nullptr;
    size_t size = 0;

    if (LoadResourceBlob(hinstance, IDR_RU_DAWG, ptr, size)) {
        words_ru_.LoadFromMemory(ptr, size);
    }
    if (LoadResourceBlob(hinstance, IDR_EN_DAWG, ptr, size)) {
        words_en_.LoadFromMemory(ptr, size);
    }
    if (LoadResourceBlob(hinstance, IDR_RU_TRIGRAMS, ptr, size)) {
        trigrams_ru_.LoadFromMemory(ptr, size);
    }
    if (LoadResourceBlob(hinstance, IDR_EN_TRIGRAMS, ptr, size)) {
        trigrams_en_.LoadFromMemory(ptr, size);
    }
    if (LoadResourceBlob(hinstance, IDR_TYPO_RULES, ptr, size)) {
        typo_rules_.LoadFromMemory(ptr, size);
    }

    detector_ = std::make_unique<LayoutDetector>(words_ru_, words_en_, trigrams_ru_, trigrams_en_);
    Keymap::Instance().Initialize();
    SnippetStore::Instance().SetSnippets(Settings::Instance().snippets);
    SoundEffect::Instance().SetEnabled(Settings::Instance().sound_enabled);

    initialized_ = words_ru_.IsLoaded() && words_en_.IsLoaded() &&
                   trigrams_ru_.IsLoaded() && trigrams_en_.IsLoaded();

    fg_event_hook_ = SetWinEventHook(EVENT_SYSTEM_FOREGROUND, EVENT_SYSTEM_FOREGROUND,
                                     nullptr, WinEventProc, 0, 0,
                                     WINEVENT_OUTOFCONTEXT | WINEVENT_SKIPOWNPROCESS);
    HWND cur_fg = GetForegroundWindow();
    if (cur_fg) OnForegroundChanged(cur_fg);

    Logger::Instance().Write(initialized_ ? "Engine: Успешно инициализирован" : "Engine: Ошибка загрузки ресурсов");
    return initialized_;
}

void Engine::Shutdown() {
    if (fg_event_hook_) {
        UnhookWinEvent(fg_event_hook_);
        fg_event_hook_ = nullptr;
    }
    TextReplacer::Instance().Stop();
    SecureInput::Instance().Shutdown();
}

static bool IsKeyDown(int vk) noexcept {
    return (GetAsyncKeyState(vk) & 0x8000) != 0;
}

void Engine::OnForegroundChanged(HWND hwnd) {
    if (!hwnd) return;
    if (hwnd == last_fg_hwnd_ && !front_process_.empty()) return;

    buf_.Clear();
    session_protected_.clear();
    current_modifiers_ = 0;
    last_fg_hwnd_ = hwnd;

    DWORD pid = 0;
    front_tid_ = GetWindowThreadProcessId(hwnd, &pid);
    front_pid_ = pid;

    HANDLE hproc = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, pid);
    if (hproc) {
        wchar_t path[MAX_PATH] = {};
        DWORD len = MAX_PATH;
        if (QueryFullProcessImageNameW(hproc, 0, path, &len)) {
            std::wstring full_path(path, len);
            size_t slash = full_path.find_last_of(L"\\/");
            front_process_ = (slash != std::wstring::npos) ? full_path.substr(slash + 1) : full_path;
        } else {
            front_process_ = L"?";
        }
        CloseHandle(hproc);
    } else {
        front_process_ = L"?";
    }

    current_app_mode_ = Settings::Instance().GetAppMode(front_process_);
}

void Engine::RefreshForeground() {
    if (!last_fg_hwnd_) {
        HWND hwnd = GetForegroundWindow();
        if (hwnd) OnForegroundChanged(hwnd);
    }
}

void Engine::HandleContextReset() {
    buf_.SoftContextReset();
    if (muted_) {
        pending_context_clear_ = true;
        return;
    }
    ApplyContextClear();
}

void Engine::ApplyContextClear() {
    pending_context_clear_ = false;
    caret_jumped_since_clear_ = true;
    backspace_since_jump_ = false;
    buf_.Clear();
    session_protected_.clear();
    anti_.ResetHistory();
}

bool Engine::OnKeyboardHook(int n_code, WPARAM w_param, const KBDLLHOOKSTRUCT& kb) {
    if (n_code < 0 || !initialized_ || paused_) return false;

    // Ignore synthetic events generated by TextReplacer
    if (kb.dwExtraInfo == SYNTH_MARKER) return false;

    bool up = (w_param == WM_KEYUP || w_param == WM_SYSKEYUP);
    bool injected = (kb.flags & LLKHF_INJECTED) != 0;
    int vk = static_cast<int>(kb.vkCode);

    if (up) {
        return OnKeyUp(vk);
    } else {
        return OnKeyDown(vk, static_cast<int>(kb.scanCode), injected);
    }
}

void Engine::OnMouseHook(int n_code, WPARAM w_param) {
    if (n_code < 0 || !initialized_ || paused_) return;
    if (front_pid_ == GetCurrentProcessId()) return;
    if (w_param == WM_LBUTTONDOWN || w_param == WM_RBUTTONDOWN ||
        w_param == WM_MBUTTONDOWN || w_param == WM_XBUTTONDOWN) {
        HandleContextReset();
    }
}

bool Engine::OnKeyUp(int vk) {
    if (front_pid_ == GetCurrentProcessId()) return false;
    switch (vk) {
        case VK_SHIFT:   case VK_LSHIFT:   case VK_RSHIFT:
            if (!IsKeyDown(VK_SHIFT)) current_modifiers_ &= ~Settings::ModShift;
            break;
        case VK_CONTROL: case VK_LCONTROL: case VK_RCONTROL:
            if (!IsKeyDown(VK_CONTROL)) current_modifiers_ &= ~Settings::ModCtrl;
            break;
        case VK_MENU:    case VK_LMENU:    case VK_RMENU:
            if (!IsKeyDown(VK_MENU)) current_modifiers_ &= ~Settings::ModAlt;
            break;
        case VK_LWIN:    case VK_RWIN:
            if (!IsKeyDown(VK_LWIN) && !IsKeyDown(VK_RWIN)) current_modifiers_ &= ~Settings::ModWin;
            break;
    }

    auto it = swallowed_ups_.find(vk);
    if (it != swallowed_ups_.end()) {
        swallowed_ups_.erase(it);
        return true;
    }
    return false;
}

bool Engine::OnKeyDown(int vk, int scan, bool injected) {
    if (front_pid_ == GetCurrentProcessId()) {
        return false;
    }

    // Modifier keys alone are not typing events
    switch (vk) {
        case VK_SHIFT:   case VK_LSHIFT:   case VK_RSHIFT:
            current_modifiers_ |= Settings::ModShift; return false;
        case VK_CONTROL: case VK_LCONTROL: case VK_RCONTROL:
            current_modifiers_ |= Settings::ModCtrl; return false;
        case VK_MENU:    case VK_LMENU:    case VK_RMENU:
            current_modifiers_ |= Settings::ModAlt; return false;
        case VK_LWIN:    case VK_RWIN:
            current_modifiers_ |= Settings::ModWin; return false;
        case 0x90 /*NumLock*/: case 0x91 /*ScrollLock*/:
            return false;
    }

    const auto& s = Settings::Instance();

    // Lockless check: increment generation so any pending boundary timer will be discarded
    boundary_gen_.fetch_add(1, std::memory_order_relaxed);

    // CapsLock remap
    if (vk == VK_CAPITAL && s.caps_remap_enabled) {
        return CapsRemap::HandleCapsKey(true, false);
    }

    int64_t now_ms = NowMilliseconds();
    auto sit = swallowed_ups_.find(vk);
    if (sit != swallowed_ups_.end() && (now_ms - sit->second < 2000)) {
        return true; // repeat of swallowed key
    }

    RefreshForeground();
    if (pending_context_clear_ && !muted_) ApplyContextClear();

    // Injected input from other applications clears our buffer
    if (injected) {
        buf_.Clear();
        return false;
    }

    // Password fields: do not buffer or modify
    if (SecureInput::Instance().CachedIsPassword(last_fg_hwnd_)) {
        SecureInput::Instance().KickAsync();
        buf_.Clear();
        return false;
    }

    bool ctrl = (current_modifiers_ & Settings::ModCtrl) != 0;
    bool alt = (current_modifiers_ & Settings::ModAlt) != 0;
    bool win = (current_modifiers_ & Settings::ModWin) != 0;
    bool shift = (current_modifiers_ & Settings::ModShift) != 0;
    bool alt_gr = ctrl && alt;
    bool command = (!alt_gr && (ctrl || alt)) || win;

    // Manual conversion hotkey
    if (vk == s.hotkey_vk && current_modifiers_ == s.hotkey_mods) {
        ConvertFromBuffer(true, false);
        swallowed_ups_[vk] = now_ms;
        return true;
    }

    switch (vk) {
        case VK_BACK:
            if (command) {
                buf_.Clear();
                backspace_since_jump_ = false;
            } else {
                buf_.Backspace();
                if (caret_jumped_since_clear_) backspace_since_jump_ = true;
            }
            return false;

        case VK_SPACE:
        case VK_TAB:
        case VK_RETURN:
            if (OnBoundary(vk, command, shift)) {
                swallowed_ups_[vk] = now_ms;
                return true;
            }
            return false;

        case VK_LEFT: case VK_UP: case VK_RIGHT: case VK_DOWN:
            buf_.ClearSessionWords();
            if (shift || s.arrows_cancel) buf_.Clear();
            return false;

        case VK_ESCAPE: case VK_DELETE: case VK_HOME: case VK_END:
        case VK_PRIOR:  case VK_NEXT:   case 0x2D /*Insert*/:
            buf_.Clear();
            return false;
    }

    // Function keys (F1-F24)
    if (vk >= 0x70 && vk <= 0x87) return false;

    if (command) {
        buf_.Clear();
        return false;
    }

    wchar_t typed = DecodeChar(vk, scan, shift);
    if (!typed) return false;

    if (muted_) in_flight_real_keys_++;

    bool first_of_word = buf_.CurrentWord().empty();
    buf_.Append(typed);

    if (first_of_word) {
        SecureInput::Instance().KickAsync();
    }

    return false;
}

void Engine::SetMessageHwnd(HWND hwnd) noexcept {
    msg_hwnd_ = hwnd;
    TextReplacer::Instance().SetMessageHwnd(hwnd);
}

wchar_t Engine::DecodeChar(int vk, int scan, bool shift) noexcept {
    HKL hkl = LayoutManager::Instance().CurrentHkl();
    BYTE state[256] = {};
    if (shift) state[VK_SHIFT] = 0x80;
    if ((GetKeyState(VK_CAPITAL) & 1) != 0) state[VK_CAPITAL] = 0x01;
    if ((GetKeyState(0x90) & 1) != 0) state[0x90] = 0x01;
    if (IsKeyDown(VK_CONTROL) && IsKeyDown(VK_MENU)) {
        state[VK_CONTROL] = 0x80;
        state[VK_MENU] = 0x80;
    }

    wchar_t buf[8] = {};
    int n = ToUnicodeEx(static_cast<UINT>(vk), static_cast<UINT>(scan), state, buf, 8, 4, hkl);
    if (n == 1 && buf[0] >= 32) {
        return buf[0];
    }
    return 0;
}

bool Engine::CheckRecentSnippet(std::wstring_view ws) {
    if (muted_ || SnippetStore::Instance().Pairs().empty()) return false;
    std::wstring recent = buf_.RecentText();
    auto match = SnippetStore::Instance().FindMatch(recent);
    if (match.has_value()) {
        SetMuted();
        Logger::Instance().Write("Snippet: автозамена триггера");
        std::wstring repl = match->expansion;
        if (!ws.empty()) {
            if (repl.empty() || (repl.back() != L' ' && repl.back() != L'\t' && repl.back() != L'\n')) {
                repl.append(ws);
            }
        }
        TextReplacer::Instance().Replace(static_cast<int>(match->trigger_length), repl);
        buf_.OnSnippetReplaced();
        return true;
    }
    return false;
}

bool Engine::CheckSnippet(std::wstring_view word) {
    return CheckRecentSnippet();
}

bool Engine::CheckTypo(std::wstring_view word) {
    const auto& s = Settings::Instance();
    if (!s.typofix_enabled || word.length() < 3) return false;

    wchar_t lower_buf[64];
    std::wstring lower_heap;
    std::wstring_view lower;
    if (word.length() < 64) {
        for (size_t i = 0; i < word.length(); ++i) lower_buf[i] = ToLower(word[i]);
        lower = std::wstring_view(lower_buf, word.length());
    } else {
        lower_heap = ToLower(word);
        lower = lower_heap;
    }

    bool cyr = HasCyrillic(lower);
    if (detector_->WordExistsInSource(lower, cyr)) return false;

    std::wstring_view fix = typo_rules_.FindCorrection(lower);
    if (!fix.empty()) {
        SetMuted();
        Logger::Instance().Write("TypoFix: автоисправление опечатки");
        std::wstring repl(fix);
        if (word.length() > 0 && ((word[0] >= L'A' && word[0] <= L'Z') || (word[0] >= 0x0410 && word[0] <= 0x042F))) {
            repl[0] = ToUpper(repl[0]);
        }
        int del = static_cast<int>(word.length());
        TextReplacer::Instance().Replace(del, repl, false, [this](bool ok) {
            EndSyntheticFlight(ok);
        });
        buf_.ApplyConversion(repl);
        return true;
    }
    return false;
}

bool Engine::OnBoundary(int vk, bool command, bool shift) {
    if (command) {
        buf_.Clear();
        return false;
    }

    const auto& s = Settings::Instance();
    std::wstring_view ws = (vk == VK_TAB) ? L"\t" : (vk == VK_RETURN) ? L"\n" : L" ";

    if (vk == VK_RETURN && ConvertBeforeReturn(shift)) {
        return true;
    }

    std::wstring_view current = buf_.CurrentWord();

    // Check snippets first (both single-word and multi-word phrases)
    if (CheckRecentSnippet(ws)) {
        return true;
    }

    // Check typo fix
    if (!current.empty() && CheckTypo(current)) {
        buf_.Boundary(ws);
        return false;
    }

    // Double space to period
    if (!buf_.LastWord().empty() && vk == VK_SPACE && s.double_space_period && current.empty() && buf_.LastTail() == L" ") {
        double gap = NowSeconds() - buf_.LastBoundaryTime();
        if (DoubleSpacePeriod::ShouldTrigger(true, gap, buf_.LastWord())) {
            SetMuted();
            Logger::Instance().Write("DoubleSpace: замена на точку с пробелом");
            TextReplacer::Instance().Replace(1, L". ");
            buf_.ApplyDoubleSpacePeriod();
            return true;
        }
    }

    buf_.Boundary(ws);
    if (muted_) in_flight_real_keys_++;

    bool auto_trigger = (vk == VK_SPACE && s.trigger_space) || (vk == VK_TAB && s.trigger_tab);
    if (current_app_mode_ == AppMode::Off) auto_trigger = false;

    if (auto_trigger && s.auto_enabled) {
        boundary_fg_ = last_fg_hwnd_;
        boundary_mode_soft_ = (current_app_mode_ == AppMode::Soft);
        boundary_gen_at_start_ = boundary_gen_.load(std::memory_order_relaxed);
        if (msg_hwnd_) {
            SetTimer(msg_hwnd_, 1001, 20, nullptr);
        }
    }

    return false;
}

void Engine::OnBoundaryTimer() {
    if (!initialized_ || paused_ || !Settings::Instance().auto_enabled) return;
    if (boundary_gen_.load(std::memory_order_relaxed) != boundary_gen_at_start_) return;
    if (last_fg_hwnd_ != boundary_fg_) return;
    ConvertFromBuffer(false, boundary_mode_soft_);
}

bool Engine::ConvertBeforeReturn(bool shift) {
    const auto& s = Settings::Instance();
    if (!s.enter_pre_convert || !s.auto_enabled || !s.trigger_enter || muted_) return false;
    if (shift || IsKeyDown(VK_CONTROL) || IsKeyDown(VK_MENU) || IsKeyDown(VK_LWIN) || IsKeyDown(VK_RWIN)) return false;
    if (current_app_mode_ == AppMode::Off) return false;

    std::wstring word = buf_.CurrentWord();
    if (word.empty()) return false;

    auto prop = AutoProposal(word, current_app_mode_ == AppMode::Soft, false);
    if (!prop.has_value()) return false;
    if (!anti_.Allow(word, prop->text)) { buf_.Clear(); return false; }
    if (SecureInput::Instance().CachedIsPassword(last_fg_hwnd_)) { buf_.Clear(); return false; }

    SetMuted();
    Logger::Instance().Write("ConvertBeforeReturn: конверсия перед переводом строки");
    TextReplacer::Instance().Replace(static_cast<int>(word.length()), prop->text, true, [this](bool ok) {
        EndSyntheticFlight(ok);
    });

    buf_.ApplyConversion(prop->text);
    buf_.Boundary(L"\n");
    LayoutManager::Instance().SelectLayout(prop->to_cyrillic);
    SoundEffect::Instance().PlaySwitchSound();
    return true;
}

std::optional<Engine::Proposal> Engine::AutoProposal(std::wstring_view word, bool soft, bool completed) {
    Keymap::Instance().RefreshDynamicIfNeeded();
    if (LayoutManager::Instance().CurrentScript() == Script::Other) return std::nullopt;

    if (!session_protected_.empty()) {
        wchar_t low_buf[64];
        std::wstring low_heap;
        std::wstring_view low;
        if (word.length() < 64) {
            for (size_t i = 0; i < word.length(); ++i) low_buf[i] = ToLower(word[i]);
            low = std::wstring_view(low_buf, word.length());
        } else {
            low_heap = ToLower(word);
            low = low_heap;
        }
        if (session_protected_.count(low) > 0) return std::nullopt;
    }

    auto rescue = detector_->MixedRescue(word);
    if (rescue.convert) {
        std::wstring converted = Keymap::Instance().Convert(word, rescue.to_cyrillic);
        return Proposal{converted, rescue.to_cyrillic, true};
    }

    bool context_for_current = !completed && !buf_.CurrentWord().empty();
    std::wstring_view prev_w = buf_.ContextWord(context_for_current);
    std::wstring_view earlier_w = buf_.EarlierContextWord(context_for_current);

    bool after_jump = caret_jumped_since_clear_;
    caret_jumped_since_clear_ = false;
    if (after_jump && word.length() == 1 && !backspace_since_jump_) after_jump = false;

    const auto& s = Settings::Instance();
    auto decision = detector_->Decide(word, s.ignored_words, s.learned_words, s.force_swap_words,
                                      prev_w, earlier_w, after_jump);
    if (!decision.convert) return std::nullopt;

    bool to_cyr = decision.to_cyrillic;

    if (soft) {
        std::wstring_view core = Keymap::Core(word);
        if (core.length() <= 2) return std::nullopt;
        double gap = completed ? buf_.LastWordGap() : buf_.CurrentWordGap();
        if (gap > 1.0) return std::nullopt;
    }

    auto is_valid = [this, to_cyr](std::wstring_view w) {
        return detector_->WordExistsInSource(w, to_cyr);
    };

    std::wstring converted = Keymap::Instance().SmartConvert(word, to_cyr, is_valid);
    if (converted == word) return std::nullopt;

    return Proposal{converted, to_cyr, false};
}

void Engine::ConvertFromBuffer(bool manual, bool soft) {
    if (paused_ || !initialized_) return;
    if (MutedStuck()) {
        if (manual) pending_manual_ = true;
        return;
    }

    const auto& s = Settings::Instance();
    if (!manual && !s.auto_enabled) return;

    Keymap::Instance().RefreshDynamicIfNeeded();

    auto target = buf_.WordForConversion(!manual);
    if (!target.has_value()) {
        if (manual && !ConvertSelection()) {
            LayoutManager::Instance().CycleLayout();
            SoundEffect::Instance().PlaySwitchSound();
        }
        return;
    }

    std::wstring word = target->word;
    int delete_count = target->delete_count;
    std::wstring tail = target->tail;

    std::wstring converted;
    bool to_cyr = false;

    if (manual) {
        to_cyr = HasCyrillic(word) ? false : HasLatin(word) ? true : !LayoutManager::Instance().CurrentIsCyrillic();
        converted = Keymap::Instance().Convert(word, to_cyr);
    } else {
        auto prop = AutoProposal(word, soft, true);
        if (!prop.has_value()) return;
        converted = prop->text;
        to_cyr = prop->to_cyrillic;
    }

    if (converted == word) return;
    if (!manual && !anti_.Allow(word, converted)) { buf_.Clear(); return; }
    if (SecureInput::Instance().IsPasswordFocused()) { buf_.Clear(); return; }
    if (!manual && last_fg_hwnd_ != GetForegroundWindow()) return;

    SetMuted();
    if (manual) {
        Logger::Instance().Write("Manual hotkey conversion");
    }

    TextReplacer::Instance().Replace(delete_count, converted + tail, false, [this](bool ok) {
        EndSyntheticFlight(ok);
    });

    if (manual) {
        buf_.ApplyConversion(converted);
        session_protected_.insert(ToLower(converted));
    } else {
        buf_.ApplyCompletedConversion(converted);
    }

    LayoutManager::Instance().SelectLayout(to_cyr);
    SoundEffect::Instance().PlaySwitchSound();
}

bool Engine::ConvertSelection() {
    std::wstring sel = SelectionText::TryGet();
    if (sel.empty() || sel.length() > 200) return false;

    bool cyr = HasCyrillic(sel);
    bool lat = HasLatin(sel);
    if (cyr == lat) return false; // Mixed or no letters

    bool to_cyr = lat;
    std::wstring converted = Keymap::Instance().Convert(sel, to_cyr);
    if (converted == sel) return false;
    if (SecureInput::Instance().IsPasswordFocused()) return false;

    SetMuted();
    Logger::Instance().Write("Selection text conversion");
    TextReplacer::Instance().Replace(0, converted, false, [this](bool ok) {
        EndSyntheticFlight(ok);
    });

    buf_.Clear();
    LayoutManager::Instance().SelectLayout(to_cyr);
    SoundEffect::Instance().PlaySwitchSound();
    return true;
}

bool Engine::MutedStuck() {
    if (!muted_) return false;
    if (NowSeconds() - muted_at_ > 1.2) {
        muted_ = false;
        Logger::Instance().Write("Engine: сброс застрявшего muted флага");
        return false;
    }
    return true;
}

void Engine::SetMuted() {
    muted_ = true;
    muted_at_ = NowSeconds();
    in_flight_real_keys_ = 0;
}

void Engine::OnSyntheticFlightFinished(bool ok) {
    if (!ok || in_flight_real_keys_ > 0) {
        buf_.Clear();
        in_flight_real_keys_ = 0;
    }
    muted_ = false;
    if (pending_context_clear_) ApplyContextClear();
    if (pending_manual_) {
        pending_manual_ = false;
        ConvertFromBuffer(true, false);
    }
}

void Engine::EndSyntheticFlight(bool ok) {
    OnSyntheticFlightFinished(ok);
}

} // namespace Ultimakey
